### ISSUE TITLE
Simplify imports

### ISSUE THREAD

**Issue by milancermak** [lindy-labs/wadray#14]
Importing from the lib is unnecessarily verbose. `use wadray::wadray::Wad` should be just `use wadray::Wad`.

For signed types, we both `use wadray::SignedWad` and `wadray::signed::SignedWad` make sense to me, but I have a slight preference for the first choice. Curious to read your thoughts.

At the same time, we should rename the repo to just `wadray` so the dependency definition would become cleaner, more consistent -> `wadray = { git = "https://github.com/lindy-labs/wadray.git" }`.

**Comment by tserg** [comment]
I have renamed this repo to `wadray`.
